### PR TITLE
Remove steam-installer package

### PR DESCRIPTION
**Pull request by jackpot51**
Required by https://github.com/pop-os/shop/pull/184
Requires https://github.com/pop-os/appstream-data/pull/23

### CODE REVIEW

**Comment by leviport** [comment]
Pop-picks features the correct "Steam" entry with the Pop .deb and the flatpak, but I'm still seeing Steam Installer show up in search results. 
steaminstaller

The correct Steam app (sources are flathub and Pop .deb):
steam-pop-flathub

The Steam Installer app (source is only Ubuntu .deb).
steaminstaller-ubuntu

Output for `apt policy steam`:
```
steam:i386:
  Installed: (none)
  Candidate: 1:1.0.0.61-2ubuntu3pop1~1588798044~20.04~d2494cc
  Version table:
     1:1.0.0.61-2ubuntu3pop1~1588798044~20.04~d2494cc 1002
       1002 http://apt.pop-os.org/staging/steam focal/main i386 Packages
        100 /var/lib/dpkg/status
     1:1.0.0.61-2ubuntu3pop1~1588014255~20.04~2d0d01d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
     1:1.0.0.61-2ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 Packages
```

And for `apt policy steam-installer`
```
steam-installer:
  Installed: (none)
  Candidate: 1.0.0.61-2ubuntu3pop1~1588014255~20.04~2d0d01d
  Version table:
     1.0.0.61-2ubuntu3pop1~1588014255~20.04~2d0d01d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
     1.0.0.61-2ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 Packages
```

**Comment by jackpot51** [comment]
I think maybe we don't need this change if the pop-shop change is released. Yes, there will be a duplicate item. But it will install the correct steam package either way

**Comment by leviport** [comment]
I think there might be something wrong with it, because attempting to install Steam installer doesn't work correctly.
Screenshot from 2020-05-12 07-59-13
The error is a dependency error:
```
The following packages have unmet dependencies:
  steam-installer: Depends: steam (= 1:1.0.0.61-2ubuntu3pop1~1588014255~20.04~2d0d01d)
```

**Comment by jackpot51** [comment]
I think there are issues with making steam-installer disappear. Closing this as I thing the appstream and shop changes are enough to get people to the right steam

**Pull request closed without merging**
