### PR TITLE
Sync with Debian packaging

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by leviport — CHANGES_REQUESTED** [review]
After installing this, I see an "Install Steam" application, instead of Steam itself:
Screenshot from 2023-11-17 16-48-03

Launching it the first time shows me this dialog:
Screenshot from 2023-11-17 16-58-35

Then Steam launches and allows me to sign in, and Steam launches normally. 

But if I exit and try re-opening Steam, the same bug is still present, where the main Steam window blinks repeatedly and never opens. This was only tested so far on a desktop with an RX 7600 so far.

**Comment by mmstick** [comment]
Since the Steam package is merely installing a script that downloads and runs the official Steam installer if Steam isn't installed on the account, I don't think updating this package will fix any driver or firmware issues. I'll prepare a linux-firmware update since that's likely where the issue is, if not I'm Mesa.

**Review by leviport — APPROVED** [review]
Not seeing any other issues with this. I think it's good to go.

**Comment by deathxxx123** [comment]
It is here on Pop!_OS from pop-shop
but install .deb from official site is ok

**Pull request merged**
